### ISSUE TITLE
[Question] Is it possible to save the session?

### ISSUE THREAD

**Issue by vladrmnv** [eilvelia/tdl#174]
Is it possible to load an already authenticated session and connect with a client, instead of authenticating on every client creation?

An example from Gramjs https://gram.js.org/getting-started/authorization#persistent-session

**Comment by eilvelia** [comment]
TDLib stores session in the `td.binlog` file, so, yes, once you're authenticated, you don't need to authenticate again on every client creation

**Comment by vladrmnv** [comment]
Thanks, would is be possible to extract sessions and move them to a different machine?

**Comment by eilvelia** [comment]
yes, you can move these files to a different machine
