### ISSUE TITLE
Missing API canSendStory

### ISSUE THREAD

**Issue by tocha688** [eilvelia/tdl#178]
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1can_send_story.html

I want to determine whether I have been banned in the group. I found this API in the documentation, but I can't use it.

**Comment by eilvelia** [comment]
As the name implies, the method checks whether you can send a story and isn't well-suitable for testing whether you are banned or not. Perhaps check `status` in https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1supergroup.html (or `basicGroup`).
